spring:
  application:
    name: eeaters-example
  datasource:
    url: jdbc:mysql://43.143.26.18:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456

  profiles:
    active: dev
