spring:
  application:
    name: eeaters-example
  datasource:
    url: jdbc:mysql://43.143.26.18:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456




third:
  wx:
    pusher:
      appToken: you appToken
      topic:
        eighty: 10501
  delivery:
    sf:
      appId: you appId
      appKey: you appKey
      productType: 10
      shopType: 2
      mock: false